/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing AuctionsCreatePostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuctionsCreatePostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuctionsCreatePostRequest
        //private AuctionsCreatePostRequest instance;

        public AuctionsCreatePostRequestTests()
        {
            // TODO uncomment below to create an instance of AuctionsCreatePostRequest
            //instance = new AuctionsCreatePostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuctionsCreatePostRequest
        /// </summary>
        [Fact]
        public void AuctionsCreatePostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuctionsCreatePostRequest
            //Assert.IsType<AuctionsCreatePostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Fact]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'StartingPrice'
        /// </summary>
        [Fact]
        public void StartingPriceTest()
        {
            // TODO unit test for the property 'StartingPrice'
        }
        /// <summary>
        /// Test the property 'BuyoutPrice'
        /// </summary>
        [Fact]
        public void BuyoutPriceTest()
        {
            // TODO unit test for the property 'BuyoutPrice'
        }
        /// <summary>
        /// Test the property 'MinimalIncrement'
        /// </summary>
        [Fact]
        public void MinimalIncrementTest()
        {
            // TODO unit test for the property 'MinimalIncrement'
        }
        /// <summary>
        /// Test the property 'MinimalReputation'
        /// </summary>
        [Fact]
        public void MinimalReputationTest()
        {
            // TODO unit test for the property 'MinimalReputation'
        }
        /// <summary>
        /// Test the property 'Private'
        /// </summary>
        [Fact]
        public void PrivateTest()
        {
            // TODO unit test for the property 'Private'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }

    }

}
