/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing AuthRegistrationPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthRegistrationPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthRegistrationPostRequest
        //private AuthRegistrationPostRequest instance;

        public AuthRegistrationPostRequestTests()
        {
            // TODO uncomment below to create an instance of AuthRegistrationPostRequest
            //instance = new AuthRegistrationPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthRegistrationPostRequest
        /// </summary>
        [Fact]
        public void AuthRegistrationPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthRegistrationPostRequest
            //Assert.IsType<AuthRegistrationPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AuthType'
        /// </summary>
        [Fact]
        public void AuthTypeTest()
        {
            // TODO unit test for the property 'AuthType'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'PasswordSecond'
        /// </summary>
        [Fact]
        public void PasswordSecondTest()
        {
            // TODO unit test for the property 'PasswordSecond'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'Recaptcha'
        /// </summary>
        [Fact]
        public void RecaptchaTest()
        {
            // TODO unit test for the property 'Recaptcha'
        }

    }

}
