/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing CurrentUserLinkedAccounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CurrentUserLinkedAccountsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CurrentUserLinkedAccounts
        //private CurrentUserLinkedAccounts instance;

        public CurrentUserLinkedAccountsTests()
        {
            // TODO uncomment below to create an instance of CurrentUserLinkedAccounts
            //instance = new CurrentUserLinkedAccounts();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CurrentUserLinkedAccounts
        /// </summary>
        [Fact]
        public void CurrentUserLinkedAccountsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CurrentUserLinkedAccounts
            //Assert.IsType<CurrentUserLinkedAccounts>(instance);
        }


        /// <summary>
        /// Test the property 'SteamProfile'
        /// </summary>
        [Fact]
        public void SteamProfileTest()
        {
            // TODO unit test for the property 'SteamProfile'
        }
        /// <summary>
        /// Test the property 'PatreonProfile'
        /// </summary>
        [Fact]
        public void PatreonProfileTest()
        {
            // TODO unit test for the property 'PatreonProfile'
        }
        /// <summary>
        /// Test the property 'XboxProfile'
        /// </summary>
        [Fact]
        public void XboxProfileTest()
        {
            // TODO unit test for the property 'XboxProfile'
        }

    }

}
