/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing DropsourceMissionsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DropsourceMissionsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DropsourceMissionsInner
        //private DropsourceMissionsInner instance;

        public DropsourceMissionsInnerTests()
        {
            // TODO uncomment below to create an instance of DropsourceMissionsInner
            //instance = new DropsourceMissionsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DropsourceMissionsInner
        /// </summary>
        [Fact]
        public void DropsourceMissionsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DropsourceMissionsInner
            //Assert.IsType<DropsourceMissionsInner>(instance);
        }


        /// <summary>
        /// Test the property 'MissionId'
        /// </summary>
        [Fact]
        public void MissionIdTest()
        {
            // TODO unit test for the property 'MissionId'
        }
        /// <summary>
        /// Test the property 'NodeId'
        /// </summary>
        [Fact]
        public void NodeIdTest()
        {
            // TODO unit test for the property 'NodeId'
        }
        /// <summary>
        /// Test the property 'Rarity'
        /// </summary>
        [Fact]
        public void RarityTest()
        {
            // TODO unit test for the property 'Rarity'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
        /// <summary>
        /// Test the property 'ItemSubtype'
        /// </summary>
        [Fact]
        public void ItemSubtypeTest()
        {
            // TODO unit test for the property 'ItemSubtype'
        }
        /// <summary>
        /// Test the property 'Rotation'
        /// </summary>
        [Fact]
        public void RotationTest()
        {
            // TODO unit test for the property 'Rotation'
        }
        /// <summary>
        /// Test the property 'Stage'
        /// </summary>
        [Fact]
        public void StageTest()
        {
            // TODO unit test for the property 'Stage'
        }

    }

}
