/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing DropsourceRelicsInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DropsourceRelicsInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DropsourceRelicsInner
        //private DropsourceRelicsInner instance;

        public DropsourceRelicsInnerTests()
        {
            // TODO uncomment below to create an instance of DropsourceRelicsInner
            //instance = new DropsourceRelicsInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DropsourceRelicsInner
        /// </summary>
        [Fact]
        public void DropsourceRelicsInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DropsourceRelicsInner
            //Assert.IsType<DropsourceRelicsInner>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Rarity'
        /// </summary>
        [Fact]
        public void RarityTest()
        {
            // TODO unit test for the property 'Rarity'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }

    }

}
