/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing GetItemInfo200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetItemInfo200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetItemInfo200Response
        //private GetItemInfo200Response instance;

        public GetItemInfo200ResponseTests()
        {
            // TODO uncomment below to create an instance of GetItemInfo200Response
            //instance = new GetItemInfo200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetItemInfo200Response
        /// </summary>
        [Fact]
        public void GetItemInfo200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetItemInfo200Response
            //Assert.IsType<GetItemInfo200Response>(instance);
        }


        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

    }

}
