/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf
        //private ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf instance;

        public ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOfTests()
        {
            // TODO uncomment below to create an instance of ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf
            //instance = new ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf
        /// </summary>
        [Fact]
        public void ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf
            //Assert.IsType<ItemsUrlNameOrdersGet200ResponsePayloadOrdersInnerAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

    }

}
