/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing ItemInOrderAllOfZhHans
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemInOrderAllOfZhHansTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemInOrderAllOfZhHans
        //private ItemInOrderAllOfZhHans instance;

        public ItemInOrderAllOfZhHansTests()
        {
            // TODO uncomment below to create an instance of ItemInOrderAllOfZhHans
            //instance = new ItemInOrderAllOfZhHans();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemInOrderAllOfZhHans
        /// </summary>
        [Fact]
        public void ItemInOrderAllOfZhHansInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemInOrderAllOfZhHans
            //Assert.IsType<ItemInOrderAllOfZhHans>(instance);
        }


        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Fact]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }

    }

}
