/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing ItemsUrlNameDropsourcesGet200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemsUrlNameDropsourcesGet200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemsUrlNameDropsourcesGet200Response
        //private ItemsUrlNameDropsourcesGet200Response instance;

        public ItemsUrlNameDropsourcesGet200ResponseTests()
        {
            // TODO uncomment below to create an instance of ItemsUrlNameDropsourcesGet200Response
            //instance = new ItemsUrlNameDropsourcesGet200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemsUrlNameDropsourcesGet200Response
        /// </summary>
        [Fact]
        public void ItemsUrlNameDropsourcesGet200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemsUrlNameDropsourcesGet200Response
            //Assert.IsType<ItemsUrlNameDropsourcesGet200Response>(instance);
        }


        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
        /// <summary>
        /// Test the property 'Include'
        /// </summary>
        [Fact]
        public void IncludeTest()
        {
            // TODO unit test for the property 'Include'
        }

    }

}
