/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing ItemInOrderAllOfEn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ItemInOrderAllOfEnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ItemInOrderAllOfEn
        //private ItemInOrderAllOfEn instance;

        public ItemInOrderAllOfEnTests()
        {
            // TODO uncomment below to create an instance of ItemInOrderAllOfEn
            //instance = new ItemInOrderAllOfEn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ItemInOrderAllOfEn
        /// </summary>
        [Fact]
        public void ItemInOrderAllOfEnInstanceTest()
        {
            // TODO uncomment below to test "IsType" ItemInOrderAllOfEn
            //Assert.IsType<ItemInOrderAllOfEn>(instance);
        }


        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Fact]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }

    }

}
