/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing LichAuction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LichAuctionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LichAuction
        //private LichAuction instance;

        public LichAuctionTests()
        {
            // TODO uncomment below to create an instance of LichAuction
            //instance = new LichAuction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LichAuction
        /// </summary>
        [Fact]
        public void LichAuctionInstanceTest()
        {
            // TODO uncomment below to test "IsType" LichAuction
            //Assert.IsType<LichAuction>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'WeaponUrlName'
        /// </summary>
        [Fact]
        public void WeaponUrlNameTest()
        {
            // TODO unit test for the property 'WeaponUrlName'
        }
        /// <summary>
        /// Test the property 'Element'
        /// </summary>
        [Fact]
        public void ElementTest()
        {
            // TODO unit test for the property 'Element'
        }
        /// <summary>
        /// Test the property 'Damage'
        /// </summary>
        [Fact]
        public void DamageTest()
        {
            // TODO unit test for the property 'Damage'
        }
        /// <summary>
        /// Test the property 'Ephemera'
        /// </summary>
        [Fact]
        public void EphemeraTest()
        {
            // TODO unit test for the property 'Ephemera'
        }
        /// <summary>
        /// Test the property 'Quirk'
        /// </summary>
        [Fact]
        public void QuirkTest()
        {
            // TODO unit test for the property 'Quirk'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
