/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing LichQuirksGet200ResponsePayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LichQuirksGet200ResponsePayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LichQuirksGet200ResponsePayload
        //private LichQuirksGet200ResponsePayload instance;

        public LichQuirksGet200ResponsePayloadTests()
        {
            // TODO uncomment below to create an instance of LichQuirksGet200ResponsePayload
            //instance = new LichQuirksGet200ResponsePayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LichQuirksGet200ResponsePayload
        /// </summary>
        [Fact]
        public void LichQuirksGet200ResponsePayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" LichQuirksGet200ResponsePayload
            //Assert.IsType<LichQuirksGet200ResponsePayload>(instance);
        }


        /// <summary>
        /// Test the property 'Quirks'
        /// </summary>
        [Fact]
        public void QuirksTest()
        {
            // TODO unit test for the property 'Quirks'
        }

    }

}
