/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing NemesisEphemera
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NemesisEphemeraTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NemesisEphemera
        //private NemesisEphemera instance;

        public NemesisEphemeraTests()
        {
            // TODO uncomment below to create an instance of NemesisEphemera
            //instance = new NemesisEphemera();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NemesisEphemera
        /// </summary>
        [Fact]
        public void NemesisEphemeraInstanceTest()
        {
            // TODO uncomment below to test "IsType" NemesisEphemera
            //Assert.IsType<NemesisEphemera>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'UrlName'
        /// </summary>
        [Fact]
        public void UrlNameTest()
        {
            // TODO unit test for the property 'UrlName'
        }
        /// <summary>
        /// Test the property 'Icon'
        /// </summary>
        [Fact]
        public void IconTest()
        {
            // TODO unit test for the property 'Icon'
        }
        /// <summary>
        /// Test the property 'IconFormat'
        /// </summary>
        [Fact]
        public void IconFormatTest()
        {
            // TODO unit test for the property 'IconFormat'
        }
        /// <summary>
        /// Test the property 'Thumb'
        /// </summary>
        [Fact]
        public void ThumbTest()
        {
            // TODO unit test for the property 'Thumb'
        }
        /// <summary>
        /// Test the property 'Animation'
        /// </summary>
        [Fact]
        public void AnimationTest()
        {
            // TODO unit test for the property 'Animation'
        }
        /// <summary>
        /// Test the property 'AnimationFormat'
        /// </summary>
        [Fact]
        public void AnimationFormatTest()
        {
            // TODO unit test for the property 'AnimationFormat'
        }
        /// <summary>
        /// Test the property 'Element'
        /// </summary>
        [Fact]
        public void ElementTest()
        {
            // TODO unit test for the property 'Element'
        }
        /// <summary>
        /// Test the property 'ItemName'
        /// </summary>
        [Fact]
        public void ItemNameTest()
        {
            // TODO unit test for the property 'ItemName'
        }

    }

}
