/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing NpcDropData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NpcDropDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NpcDropData
        //private NpcDropData instance;

        public NpcDropDataTests()
        {
            // TODO uncomment below to create an instance of NpcDropData
            //instance = new NpcDropData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NpcDropData
        /// </summary>
        [Fact]
        public void NpcDropDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" NpcDropData
            //Assert.IsType<NpcDropData>(instance);
        }


        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'Npc'
        /// </summary>
        [Fact]
        public void NpcTest()
        {
            // TODO unit test for the property 'Npc'
        }
        /// <summary>
        /// Test the property 'Rate'
        /// </summary>
        [Fact]
        public void RateTest()
        {
            // TODO unit test for the property 'Rate'
        }
        /// <summary>
        /// Test the property 'Rarity'
        /// </summary>
        [Fact]
        public void RarityTest()
        {
            // TODO unit test for the property 'Rarity'
        }

    }

}
