/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing ProfileOrdersPostRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProfileOrdersPostRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProfileOrdersPostRequest
        //private ProfileOrdersPostRequest instance;

        public ProfileOrdersPostRequestTests()
        {
            // TODO uncomment below to create an instance of ProfileOrdersPostRequest
            //instance = new ProfileOrdersPostRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProfileOrdersPostRequest
        /// </summary>
        [Fact]
        public void ProfileOrdersPostRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProfileOrdersPostRequest
            //Assert.IsType<ProfileOrdersPostRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Fact]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'Platinum'
        /// </summary>
        [Fact]
        public void PlatinumTest()
        {
            // TODO unit test for the property 'Platinum'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Fact]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }
        /// <summary>
        /// Test the property 'Rank'
        /// </summary>
        [Fact]
        public void RankTest()
        {
            // TODO unit test for the property 'Rank'
        }
        /// <summary>
        /// Test the property 'Subtype'
        /// </summary>
        [Fact]
        public void SubtypeTest()
        {
            // TODO unit test for the property 'Subtype'
        }

    }

}
