/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing ProfileOrdersPost200ResponsePayloadOrder
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProfileOrdersPost200ResponsePayloadOrderTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProfileOrdersPost200ResponsePayloadOrder
        //private ProfileOrdersPost200ResponsePayloadOrder instance;

        public ProfileOrdersPost200ResponsePayloadOrderTests()
        {
            // TODO uncomment below to create an instance of ProfileOrdersPost200ResponsePayloadOrder
            //instance = new ProfileOrdersPost200ResponsePayloadOrder();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProfileOrdersPost200ResponsePayloadOrder
        /// </summary>
        [Fact]
        public void ProfileOrdersPost200ResponsePayloadOrderInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProfileOrdersPost200ResponsePayloadOrder
            //Assert.IsType<ProfileOrdersPost200ResponsePayloadOrder>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Platinum'
        /// </summary>
        [Fact]
        public void PlatinumTest()
        {
            // TODO unit test for the property 'Platinum'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Fact]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Fact]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'LastUpdate'
        /// </summary>
        [Fact]
        public void LastUpdateTest()
        {
            // TODO unit test for the property 'LastUpdate'
        }
        /// <summary>
        /// Test the property 'Subtype'
        /// </summary>
        [Fact]
        public void SubtypeTest()
        {
            // TODO unit test for the property 'Subtype'
        }
        /// <summary>
        /// Test the property 'Visible'
        /// </summary>
        [Fact]
        public void VisibleTest()
        {
            // TODO unit test for the property 'Visible'
        }
        /// <summary>
        /// Test the property 'Item'
        /// </summary>
        [Fact]
        public void ItemTest()
        {
            // TODO unit test for the property 'Item'
        }

    }

}
