/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing RivenAuctionAttributesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RivenAuctionAttributesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RivenAuctionAttributesInner
        //private RivenAuctionAttributesInner instance;

        public RivenAuctionAttributesInnerTests()
        {
            // TODO uncomment below to create an instance of RivenAuctionAttributesInner
            //instance = new RivenAuctionAttributesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RivenAuctionAttributesInner
        /// </summary>
        [Fact]
        public void RivenAuctionAttributesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" RivenAuctionAttributesInner
            //Assert.IsType<RivenAuctionAttributesInner>(instance);
        }


        /// <summary>
        /// Test the property 'Positive'
        /// </summary>
        [Fact]
        public void PositiveTest()
        {
            // TODO unit test for the property 'Positive'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'UrlName'
        /// </summary>
        [Fact]
        public void UrlNameTest()
        {
            // TODO unit test for the property 'UrlName'
        }

    }

}
