/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing SettingsNotificationsPushPostRequestOneOf1Subscription
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettingsNotificationsPushPostRequestOneOf1SubscriptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SettingsNotificationsPushPostRequestOneOf1Subscription
        //private SettingsNotificationsPushPostRequestOneOf1Subscription instance;

        public SettingsNotificationsPushPostRequestOneOf1SubscriptionTests()
        {
            // TODO uncomment below to create an instance of SettingsNotificationsPushPostRequestOneOf1Subscription
            //instance = new SettingsNotificationsPushPostRequestOneOf1Subscription();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettingsNotificationsPushPostRequestOneOf1Subscription
        /// </summary>
        [Fact]
        public void SettingsNotificationsPushPostRequestOneOf1SubscriptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" SettingsNotificationsPushPostRequestOneOf1Subscription
            //Assert.IsType<SettingsNotificationsPushPostRequestOneOf1Subscription>(instance);
        }


        /// <summary>
        /// Test the property 'PushToken'
        /// </summary>
        [Fact]
        public void PushTokenTest()
        {
            // TODO unit test for the property 'PushToken'
        }

    }

}
