/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using WarframeMarket.Model;
using WarframeMarket.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace WarframeMarket.Test.Model
{
    /// <summary>
    ///  Class for testing UserShort
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserShortTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserShort
        //private UserShort instance;

        public UserShortTests()
        {
            // TODO uncomment below to create an instance of UserShort
            //instance = new UserShort();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserShort
        /// </summary>
        [Fact]
        public void UserShortInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserShort
            //Assert.IsType<UserShort>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IngameName'
        /// </summary>
        [Fact]
        public void IngameNameTest()
        {
            // TODO unit test for the property 'IngameName'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Reputation'
        /// </summary>
        [Fact]
        public void ReputationTest()
        {
            // TODO unit test for the property 'Reputation'
        }
        /// <summary>
        /// Test the property 'Avatar'
        /// </summary>
        [Fact]
        public void AvatarTest()
        {
            // TODO unit test for the property 'Avatar'
        }
        /// <summary>
        /// Test the property 'LastSeen'
        /// </summary>
        [Fact]
        public void LastSeenTest()
        {
            // TODO unit test for the property 'LastSeen'
        }

    }

}
