/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WarframeMarket.Client.OpenAPIDateConverter;
using System.Reflection;

namespace WarframeMarket.Model
{
    /// <summary>
    /// AuctionsCreatePostRequestItem
    /// </summary>
    [JsonConverter(typeof(AuctionsCreatePostRequestItemJsonConverter))]
    [DataContract(Name = "_auctions_create_post_request_item")]
    public partial class AuctionsCreatePostRequestItem : AbstractOpenAPISchema, IEquatable<AuctionsCreatePostRequestItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuctionsCreatePostRequestItem" /> class
        /// with the <see cref="RivenAuction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of RivenAuction.</param>
        public AuctionsCreatePostRequestItem(RivenAuction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuctionsCreatePostRequestItem" /> class
        /// with the <see cref="LichAuction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of LichAuction.</param>
        public AuctionsCreatePostRequestItem(LichAuction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuctionsCreatePostRequestItem" /> class
        /// with the <see cref="KubrowAuction" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of KubrowAuction.</param>
        public AuctionsCreatePostRequestItem(KubrowAuction actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(KubrowAuction))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(LichAuction))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(RivenAuction))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: KubrowAuction, LichAuction, RivenAuction");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `RivenAuction`. If the actual instance is not `RivenAuction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of RivenAuction</returns>
        public RivenAuction GetRivenAuction()
        {
            return (RivenAuction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `LichAuction`. If the actual instance is not `LichAuction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of LichAuction</returns>
        public LichAuction GetLichAuction()
        {
            return (LichAuction)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `KubrowAuction`. If the actual instance is not `KubrowAuction`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of KubrowAuction</returns>
        public KubrowAuction GetKubrowAuction()
        {
            return (KubrowAuction)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AuctionsCreatePostRequestItem {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, AuctionsCreatePostRequestItem.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of AuctionsCreatePostRequestItem
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of AuctionsCreatePostRequestItem</returns>
        public static AuctionsCreatePostRequestItem FromJson(string jsonString)
        {
            AuctionsCreatePostRequestItem newAuctionsCreatePostRequestItem = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newAuctionsCreatePostRequestItem;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(KubrowAuction).GetProperty("AdditionalProperties") == null)
                {
                    newAuctionsCreatePostRequestItem = new AuctionsCreatePostRequestItem(JsonConvert.DeserializeObject<KubrowAuction>(jsonString, AuctionsCreatePostRequestItem.SerializerSettings));
                }
                else
                {
                    newAuctionsCreatePostRequestItem = new AuctionsCreatePostRequestItem(JsonConvert.DeserializeObject<KubrowAuction>(jsonString, AuctionsCreatePostRequestItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("KubrowAuction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into KubrowAuction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(LichAuction).GetProperty("AdditionalProperties") == null)
                {
                    newAuctionsCreatePostRequestItem = new AuctionsCreatePostRequestItem(JsonConvert.DeserializeObject<LichAuction>(jsonString, AuctionsCreatePostRequestItem.SerializerSettings));
                }
                else
                {
                    newAuctionsCreatePostRequestItem = new AuctionsCreatePostRequestItem(JsonConvert.DeserializeObject<LichAuction>(jsonString, AuctionsCreatePostRequestItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("LichAuction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into LichAuction: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(RivenAuction).GetProperty("AdditionalProperties") == null)
                {
                    newAuctionsCreatePostRequestItem = new AuctionsCreatePostRequestItem(JsonConvert.DeserializeObject<RivenAuction>(jsonString, AuctionsCreatePostRequestItem.SerializerSettings));
                }
                else
                {
                    newAuctionsCreatePostRequestItem = new AuctionsCreatePostRequestItem(JsonConvert.DeserializeObject<RivenAuction>(jsonString, AuctionsCreatePostRequestItem.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("RivenAuction");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into RivenAuction: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newAuctionsCreatePostRequestItem;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuctionsCreatePostRequestItem);
        }

        /// <summary>
        /// Returns true if AuctionsCreatePostRequestItem instances are equal
        /// </summary>
        /// <param name="input">Instance of AuctionsCreatePostRequestItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuctionsCreatePostRequestItem input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for AuctionsCreatePostRequestItem
    /// </summary>
    public class AuctionsCreatePostRequestItemJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(AuctionsCreatePostRequestItem).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return AuctionsCreatePostRequestItem.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
