/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WarframeMarket.Client.OpenAPIDateConverter;

namespace WarframeMarket.Model
{
    /// <summary>
    /// GetItemInfo200ResponsePayloadItem
    /// </summary>
    [DataContract(Name = "getItemInfo_200_response_payload_item")]
    public partial class GetItemInfo200ResponsePayloadItem : IEquatable<GetItemInfo200ResponsePayloadItem>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetItemInfo200ResponsePayloadItem" /> class.
        /// </summary>
        /// <param name="id">Object id of requested item.</param>
        /// <param name="itemsInSet">itemsInSet.</param>
        public GetItemInfo200ResponsePayloadItem(string id = default(string), List<ItemFull> itemsInSet = default(List<ItemFull>))
        {
            this.Id = id;
            this.ItemsInSet = itemsInSet;
        }

        /// <summary>
        /// Object id of requested item
        /// </summary>
        /// <value>Object id of requested item</value>
        /// <example>5a2feeb2c2c9e90cbdaa23d4</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ItemsInSet
        /// </summary>
        [DataMember(Name = "items_in_set", EmitDefaultValue = false)]
        public List<ItemFull> ItemsInSet { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetItemInfo200ResponsePayloadItem {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ItemsInSet: ").Append(ItemsInSet).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetItemInfo200ResponsePayloadItem);
        }

        /// <summary>
        /// Returns true if GetItemInfo200ResponsePayloadItem instances are equal
        /// </summary>
        /// <param name="input">Instance of GetItemInfo200ResponsePayloadItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetItemInfo200ResponsePayloadItem input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.ItemsInSet == input.ItemsInSet ||
                    this.ItemsInSet != null &&
                    input.ItemsInSet != null &&
                    this.ItemsInSet.SequenceEqual(input.ItemsInSet)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                if (this.ItemsInSet != null)
                {
                    hashCode = (hashCode * 59) + this.ItemsInSet.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
