/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WarframeMarket.Client.OpenAPIDateConverter;

namespace WarframeMarket.Model
{
    /// <summary>
    /// LichWeaponsGet200ResponsePayload
    /// </summary>
    [DataContract(Name = "_lich_weapons_get_200_response_payload")]
    public partial class LichWeaponsGet200ResponsePayload : IEquatable<LichWeaponsGet200ResponsePayload>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LichWeaponsGet200ResponsePayload" /> class.
        /// </summary>
        /// <param name="weapons">weapons.</param>
        public LichWeaponsGet200ResponsePayload(List<NemesisWeapon> weapons = default(List<NemesisWeapon>))
        {
            this.Weapons = weapons;
        }

        /// <summary>
        /// Gets or Sets Weapons
        /// </summary>
        [DataMember(Name = "weapons", EmitDefaultValue = false)]
        public List<NemesisWeapon> Weapons { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LichWeaponsGet200ResponsePayload {\n");
            sb.Append("  Weapons: ").Append(Weapons).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LichWeaponsGet200ResponsePayload);
        }

        /// <summary>
        /// Returns true if LichWeaponsGet200ResponsePayload instances are equal
        /// </summary>
        /// <param name="input">Instance of LichWeaponsGet200ResponsePayload to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LichWeaponsGet200ResponsePayload input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Weapons == input.Weapons ||
                    this.Weapons != null &&
                    input.Weapons != null &&
                    this.Weapons.SequenceEqual(input.Weapons)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Weapons != null)
                {
                    hashCode = (hashCode * 59) + this.Weapons.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
