/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WarframeMarket.Client.OpenAPIDateConverter;

namespace WarframeMarket.Model
{
    /// <summary>
    /// SettingsNotificationsPushPostRequestOneOf1Subscription
    /// </summary>
    [DataContract(Name = "_settings_notifications_push_post_request_oneOf_1_subscription")]
    public partial class SettingsNotificationsPushPostRequestOneOf1Subscription : IEquatable<SettingsNotificationsPushPostRequestOneOf1Subscription>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsNotificationsPushPostRequestOneOf1Subscription" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SettingsNotificationsPushPostRequestOneOf1Subscription() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsNotificationsPushPostRequestOneOf1Subscription" /> class.
        /// </summary>
        /// <param name="pushToken">pushToken (required).</param>
        public SettingsNotificationsPushPostRequestOneOf1Subscription(string pushToken = default(string))
        {
            // to ensure "pushToken" is required (not null)
            if (pushToken == null)
            {
                throw new ArgumentNullException("pushToken is a required property for SettingsNotificationsPushPostRequestOneOf1Subscription and cannot be null");
            }
            this.PushToken = pushToken;
        }

        /// <summary>
        /// Gets or Sets PushToken
        /// </summary>
        [DataMember(Name = "push_token", IsRequired = true, EmitDefaultValue = true)]
        public string PushToken { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SettingsNotificationsPushPostRequestOneOf1Subscription {\n");
            sb.Append("  PushToken: ").Append(PushToken).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SettingsNotificationsPushPostRequestOneOf1Subscription);
        }

        /// <summary>
        /// Returns true if SettingsNotificationsPushPostRequestOneOf1Subscription instances are equal
        /// </summary>
        /// <param name="input">Instance of SettingsNotificationsPushPostRequestOneOf1Subscription to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SettingsNotificationsPushPostRequestOneOf1Subscription input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PushToken == input.PushToken ||
                    (this.PushToken != null &&
                    this.PushToken.Equals(input.PushToken))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PushToken != null)
                {
                    hashCode = (hashCode * 59) + this.PushToken.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
