/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = WarframeMarket.Client.OpenAPIDateConverter;

namespace WarframeMarket.Model
{
    /// <summary>
    /// SettingsNotificationsPushPostRequestOneOf
    /// </summary>
    [DataContract(Name = "_settings_notifications_push_post_request_oneOf")]
    public partial class SettingsNotificationsPushPostRequestOneOf : IEquatable<SettingsNotificationsPushPostRequestOneOf>, IValidatableObject
    {
        /// <summary>
        /// Defines Device
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DeviceEnum
        {
            /// <summary>
            /// Enum Web for value: web
            /// </summary>
            [EnumMember(Value = "web")]
            Web = 1
        }


        /// <summary>
        /// Gets or Sets Device
        /// </summary>
        [DataMember(Name = "device", IsRequired = true, EmitDefaultValue = true)]
        public DeviceEnum Device { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsNotificationsPushPostRequestOneOf" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SettingsNotificationsPushPostRequestOneOf() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SettingsNotificationsPushPostRequestOneOf" /> class.
        /// </summary>
        /// <param name="device">device (required).</param>
        /// <param name="subscription">subscription (required).</param>
        public SettingsNotificationsPushPostRequestOneOf(DeviceEnum device = default(DeviceEnum), SettingsNotificationsPushPostRequestOneOfSubscription subscription = default(SettingsNotificationsPushPostRequestOneOfSubscription))
        {
            this.Device = device;
            // to ensure "subscription" is required (not null)
            if (subscription == null)
            {
                throw new ArgumentNullException("subscription is a required property for SettingsNotificationsPushPostRequestOneOf and cannot be null");
            }
            this.Subscription = subscription;
        }

        /// <summary>
        /// Gets or Sets Subscription
        /// </summary>
        [DataMember(Name = "subscription", IsRequired = true, EmitDefaultValue = true)]
        public SettingsNotificationsPushPostRequestOneOfSubscription Subscription { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SettingsNotificationsPushPostRequestOneOf {\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("  Subscription: ").Append(Subscription).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SettingsNotificationsPushPostRequestOneOf);
        }

        /// <summary>
        /// Returns true if SettingsNotificationsPushPostRequestOneOf instances are equal
        /// </summary>
        /// <param name="input">Instance of SettingsNotificationsPushPostRequestOneOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SettingsNotificationsPushPostRequestOneOf input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Device == input.Device ||
                    this.Device.Equals(input.Device)
                ) && 
                (
                    this.Subscription == input.Subscription ||
                    (this.Subscription != null &&
                    this.Subscription.Equals(input.Subscription))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Device.GetHashCode();
                if (this.Subscription != null)
                {
                    hashCode = (hashCode * 59) + this.Subscription.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
