/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using WarframeMarket.Client;
using WarframeMarket.Api;
// uncomment below to import models
//using WarframeMarket.Model;

namespace WarframeMarket.Test.Api
{
    /// <summary>
    ///  Class for testing AuthApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AuthApiTests : IDisposable
    {
        private AuthApi instance;

        public AuthApiTests()
        {
            instance = new AuthApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AuthApi
            //Assert.IsType<AuthApi>(instance);
        }

        /// <summary>
        /// Test AuthRegistrationPost
        /// </summary>
        [Fact]
        public void AuthRegistrationPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AuthRegistrationPostRequest authRegistrationPostRequest = null;
            //var response = instance.AuthRegistrationPost(authRegistrationPostRequest);
            //Assert.IsType<CurrentUser>(response);
        }

        /// <summary>
        /// Test AuthRestorePost
        /// </summary>
        [Fact]
        public void AuthRestorePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AuthRestorePostRequest authRestorePostRequest = null;
            //var response = instance.AuthRestorePost(authRestorePostRequest);
            //Assert.IsType<Object>(response);
        }

        /// <summary>
        /// Test AuthSigninPost
        /// </summary>
        [Fact]
        public void AuthSigninPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AuthSigninPostRequest authSigninPostRequest = null;
            //var response = instance.AuthSigninPost(authSigninPostRequest);
            //Assert.IsType<CurrentUser>(response);
        }
    }
}
