/*
 * Warframe.market API
 *
 * ## Documentation is under very slow and heavy development  This document will gradually be supplemented and updated over some extended period of time.  ## Unstable endpoints Endpoint that is not stable and probably will be changed in the future will be marked with exclamation sign -> ⚠ 
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using WarframeMarket.Client;
using WarframeMarket.Api;
// uncomment below to import models
//using WarframeMarket.Model;

namespace WarframeMarket.Test.Api
{
    /// <summary>
    ///  Class for testing SistersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SistersApiTests : IDisposable
    {
        private SistersApi instance;

        public SistersApiTests()
        {
            instance = new SistersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SistersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SistersApi
            //Assert.IsType<SistersApi>(instance);
        }

        /// <summary>
        /// Test SisterEphermerasGet
        /// </summary>
        [Fact]
        public void SisterEphermerasGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string language = null;
            //var response = instance.SisterEphermerasGet(language);
            //Assert.IsType<LichEphemerasGet200Response>(response);
        }

        /// <summary>
        /// Test SisterQuirksGet
        /// </summary>
        [Fact]
        public void SisterQuirksGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string language = null;
            //var response = instance.SisterQuirksGet(language);
            //Assert.IsType<LichQuirksGet200Response>(response);
        }

        /// <summary>
        /// Test SisterWeaponsGet
        /// </summary>
        [Fact]
        public void SisterWeaponsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string language = null;
            //var response = instance.SisterWeaponsGet(language);
            //Assert.IsType<LichWeaponsGet200Response>(response);
        }
    }
}
